AWSTemplateFormatVersion: 2010-09-09

Description: Creates a new S3 bucket in the same region as this stack, configured to host the static DotKEGG documentation, as well as several buckets/DNS record sets for redirecting web requests to the DotKEGG domain names.
  
Resources:
  # S3 bucket for hosting the static documentation
  ComDocsBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: docs.dotkegg.com
      LoggingConfiguration:
        DestinationBucketName: danware-us-east-2-logs
        LogFilePrefix: docs/dotkegg/
      WebsiteConfiguration:
        #ErrorDocument: 
        IndexDocument: index.html
        
  # S3 buckets for web redirects
  NetBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: dotkegg.net
      LoggingConfiguration:
        DestinationBucketName: danware-us-east-2-logs
        LogFilePrefix: redirect/dotkegg.net/
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: www.danwarecreations.com/products/dotkegg/
          Protocol: https
  NetWwwBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: www.dotkegg.net
      LoggingConfiguration:
        DestinationBucketName: danware-us-east-2-logs
        LogFilePrefix: redirect/www.dotkegg.net/
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: www.danwarecreations.com/products/dotkegg/
          Protocol: https
          
  OrgBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: dotkegg.org
      LoggingConfiguration:
        DestinationBucketName: danware-us-east-2-logs
        LogFilePrefix: redirect/dotkegg.org/
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: www.danwarecreations.com/products/dotkegg/
          Protocol: https
  OrgWwwBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: www.dotkegg.org
      LoggingConfiguration:
        DestinationBucketName: danware-us-east-2-logs
        LogFilePrefix: redirect/www.dotkegg.org/
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: www.danwarecreations.com/products/dotkegg/
          Protocol: https
          
  ComBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: dotkegg.com
      LoggingConfiguration:
        DestinationBucketName: danware-us-east-2-logs
        LogFilePrefix: redirect/dotkegg.com/
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: www.danwarecreations.com/products/dotkegg/
          Protocol: https
  ComWwwBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: www.dotkegg.com
      LoggingConfiguration:
        DestinationBucketName: danware-us-east-2-logs
        LogFilePrefix: redirect/www.dotkegg.com/
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: www.danwarecreations.com/products/dotkegg/
          Protocol: https

  # IAM Group with permissions to manage the documentation-hosting S3 bucket
  UploadDocsGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: dotkegg-docs-admins
      Path: /dotkegg-docs-admins/
      Policies:
        - PolicyName: ManageDotKeggDocsBucket
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - # Allow managing of the DotKEGG documentation bucket ONLY
              Sid: 1
              Effect: Allow
              Action: s3:*
              Resource: !Join [ "", [ "arn:aws:s3:::", !Ref ComDocsBucket ] ]
      
  # Route 53 Record Set Groups
  NetDnsRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: dotkegg.net.
      Comment: redirect rules for the DotKEGG .net domain
      RecordSets:
      - # Redirect docs subdomain to docs subdomain of .com domain
        Name: docs.dotkegg.net
        Type: CNAME
        ResourceRecords: [ docs.dotkegg.com ]
        TTL: 60
        # HealthCheckId: String
      - # Redirect zone apex to DotKEGG website (can't use CNAME for zone apex, nor for when the target URL contains a path)
        Name: dotkegg.net
        AliasTarget:
          DNSName: s3-website.us-east-2.amazonaws.com
          HostedZoneId: Z2O1EMRO9K5GLX
        Type: A   # Actually means S3 since this is an Alias record set
        # HealthCheckId: String
      - # Redirect www subdomain to DotKEGG website (can't use CNAME since the target URL contains a path)
        Name: www.dotkegg.net
        AliasTarget:
          DNSName: s3-website.us-east-2.amazonaws.com
          HostedZoneId: Z2O1EMRO9K5GLX
        Type: A   # Actually means S3 since this is an Alias record set
        # HealthCheckId: String
  OrgDnsRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: dotkegg.org.
      Comment: redirect rules for the DotKEGG .org domain
      RecordSets:
      - # Redirect docs subdomain to docs subdomain of .com domain
        Name: docs.dotkegg.org
        Type: CNAME
        ResourceRecords: [ docs.dotkegg.com ]
        TTL: 60
        # HealthCheckId: String
      - # Redirect zone apex to DotKEGG website (can't use CNAME for zone apex, nor for when the target URL contains a path)
        Name: dotkegg.org
        AliasTarget:
          DNSName: s3-website.us-east-2.amazonaws.com
          HostedZoneId: Z2O1EMRO9K5GLX
        Type: A   # Actually means S3 since this is an Alias record set
        # HealthCheckId: String
      - # Redirect www subdomain to DotKEGG website (can't use CNAME since the target URL contains a path)
        Name: www.dotkegg.org
        AliasTarget:
          DNSName: s3-website.us-east-2.amazonaws.com
          HostedZoneId: Z2O1EMRO9K5GLX
        Type: A   # Actually means S3 since this is an Alias record set
        # HealthCheckId: String
  ComDnsRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: dotkegg.com.
      Comment: redirect rules for the DotKEGG .com domain
      RecordSets:
      - # Redirect docs subdomain to DotKEGG documentation hosted in S3 bucket
        Name: docs.dotkegg.com
        AliasTarget:
          DNSName: s3-website.us-east-2.amazonaws.com
          HostedZoneId: Z2O1EMRO9K5GLX
        Type: A   # Actually means S3 since this is an Alias record set
        # HealthCheckId: String
      - # Redirect zone apex to DotKEGG website (can't use CNAME for zone apex, nor for when the target URL contains a path)
        Name: dotkegg.com
        AliasTarget:
          DNSName: s3-website.us-east-2.amazonaws.com
          HostedZoneId: Z2O1EMRO9K5GLX
        Type: A   # Actually means S3 since this is an Alias record set
        # HealthCheckId: String
      - # Redirect www subdomain to DotKEGG website (can't use CNAME since the target URL contains a path)
        Name: www.dotkegg.com
        AliasTarget:
          DNSName: s3-website.us-east-2.amazonaws.com
          HostedZoneId: Z2O1EMRO9K5GLX
        Type: A   # Actually means S3 since this is an Alias record set
        # HealthCheckId: String
          
Outputs:
  DocsHostBucket:
    Value: !Ref ComDocsBucket
    Description: Name of the new AWS S3 bucket that will host the static documentation.
